### ISSUE TITLE
Tiling buttons don't work for maximized windows

### ISSUE THREAD

**Issue by ccvormann** [domferr/tilingshell#113]
**Describe the bug**
When a window is maximized, the tiling buttons appear but do not work. 

**To Reproduce**
1. Maximize a window
2. right click on the title bar, the tiling buttons appear
3. Click on any tile in any layout
4. The window is not tiled but remains maximized
5. Drag window to smaller size, the tiling buttons work

**Information (please complete the following):**
 - Tiling Shell version: v23
 - GNOME version: 46 on Fedora 40

**Comment by richardnpaul** [comment]
I can confirm replication of these steps on Ubuntu 22.04, Gnome 42.9 and the latest version of Tiling Shell.

I'd rewrite the description as when a window is maximised, right clicking the application bar and using any of the tiling options in the context menu does not result in the expected behaviour.
[Screencast-from-31-07-24-12:38:00.webm](https://github.com/user-attachments/assets/5598e903-967d-4fdc-973d-f39da46bc392)

**Comment by domferr** [comment]
Hey thank you for reporting this! The current implementation doesn't allow to tile when a window is maximised. This is going to be fixed in the next update :smile:

**Comment by domferr** [comment]
:heavy_check_mark: Done in version 12.2! The new version is already available on GSE
<div align="center">
  <a href="https://extensions.gnome.org/extension/7065/tiling-shell/" >
      <img src="https://img.shields.io/badge/Install%20from-extensions.gnome.org-4A86CF?style=for-the-badge&logo=Gnome&logoColor=white"/>
  </a>
</div>
