### ISSUE TITLE
[BUG] SUPER + LEFT_ARROW doesn't work when a window was maximized.

### ISSUE THREAD

**Issue by thyttan** [domferr/tilingshell#59]
**Describe the bug**
- `SUPER` + `LEFT_ARROW` doesn't do anything when a window was maximized. 
- `SUPER` + `RIGHT_ARROW` moves the window into the `top left` layout position if it was previously maximized.

**To Reproduce**
1. Do `SUPER` + `UP_ARROW` until the window is maximized.
2. Do `SUPER` + `LEFT_ARROW` and notice nothing happens.
3. Do `SUPER` + `RIGHT_ARROW` and see the window snap to the `top left` layout position.

**Expected behaviour**
- `SUPER` + `LEFT_ARROW` should move the window to the `top left` layout position. 
- `SUPER` + `RIGHT_ARROW` should move the window to the `top right` layout position.
- (`SUPER` + `DOWN_ARROW` should restore the window to where it was before being maximized - as it already does today in version 10.0 so don't change it! 😀 )

**Information:**
 - Tiling Shell version: 10.0
 - GNOME version: 46.2

**Comment by domferr** [comment]
Hey @thyttan thank you for reporting this bug! Your report is AWESOME, it is very well made, thank you :heart:!
This will be fixed in the next update, meanwhile I leave here the files if you want to try it in advance. If you do, let me know if it is fixed and if the other keybindings are working like before! Thank you

- GNOME 42, 43 or 44: [GNOME.42-44.tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16026498/GNOME.42-44.tilingshell%40ferrarodomenico.com.zip)
- GNOME 45 or 46: [tilingshell@ferrarodomenico.com.zip](https://github.com/user-attachments/files/16026502/tilingshell%40ferrarodomenico.com.zip)

**Comment by thyttan** [comment]
Thanks! The bug went away with that fix!

**Comment by twkonefal** [comment]
I have a similar issue. When using multiple monitors the SUPER + ARROW doesn't move the window to the next monitor if unless the window is fully maximized or un-tiled. If you SUPER + ARROW the window to an edge on one monitor you can't repeat the command (or use SUPER+SHIFT+ARROW) to move the window to the next monitor. I feel like this used to work, but it no longer does.

**Comment by domferr** [comment]
Hey @twkonefal, Tiling Shell's keybindings doesn't move the window to another monitor, so I suspect you were using GNOME's keybindings. If you want that behavior, you can disable Tiling Shell's keybindings from the preferences, which will automatically re-enable GNOME's ones. I hope to add the feature you are talking about in the future!
