### ISSUE TITLE
[Feature Request] Preview Animations and Transparency Customizations

### ISSUE THREAD

**Issue by ottaviomarco** [domferr/tilingshell#61]
**Describe the feature you'd like**
The ability to disable edge tiling and preview animations (speeding them up could be nice too, full-screen one is somehow jerky). The ability to change tiling preview transparency and color, and rearrange zone layouts could be nice additions too.

**Additional context**
Admittedly, I prefer the v9 version. I always hated how difficult it is to place a window next to the top panel without triggering the full-screen snap animation.

**Comment by domferr** [comment]
Hey @ottaviomarco thank you for your suggestion! I agree with you.

- Speaking about **enabling/disabling animations**, I was working on it but encountered some bugs, so that feature got delayed.
- The good news is that I already planned to allow **enable/disable the edge-tiling** in the next minor update :partying_face: and **customizing colors** in the next major release.

If you are interested into rearranging layouts you can follow the issue #22 that is tracking that. Meanwhile, if you want to rearrange them now, you have the following options:
- play with importing and exporting layouts multiple times to achieve the desired order
- exporting the layouts, edit the JSON file to achieve the order you want, and then importing them

Thank you for your feedback! Enjoy Tiling Shell :heart:

**Comment by domferr** [comment]
Update: enable/disable the edge-tiling is now landing with the next release! :partying_face:

**Comment by domferr** [comment]
:star2: Now available in [Tiling Shell v14](https://github.com/domferr/tilingshell/releases/tag/14.0)!
