### ISSUE TITLE
Where to find preferences menu

### ISSUE THREAD

**Issue by lassieee** [domferr/tilingshell#67]
**Describe the bug**
Unable to find plugin preferences menu.

First of all, love your plugin, thanks for open-sourcing it!
I'd like to remove the blanc space between windows. I tried editing the prefs.js which didn't work. I see screenshots showing a preferences menu but I've no idea how to access that.

I only have this tiling shell icon in the system tray with the following options:
![Screenshot from 2024-07-01 20-31-00](https://github.com/domferr/tilingshell/assets/4531126/83b84ff2-c9a2-42f0-85c1-d9863624b448)

**To Reproduce**
1) download latest version of plugin
2) follow installation instructions
3) logout and log back in

**Information (please complete the following):**
 - Tiling Shell version: v10.0
 - GNOME version: 42 (ubuntu 20.04)

**Comment by domferr** [comment]
Hey! Every extension has its own preferences window. It can be accessed in multiple ways. The easiest is from the extension webpage (https://extensions.gnome.org/extension/7065/tiling-shell/).
<p align="center">
<img src="https://github.com/domferr/tilingshell/assets/14203981/b30f32ee-1719-4d0a-8caa-5bec6a841ab9" />
</p>

Personally, I use Extension Manager. You can find out more here https://www.baeldung.com/linux/gnome-shell-extension.

Otherwise, you can run `gnome-extensions prefs tilingshell@ferrarodomenico.com`.

**Comment by lassieee** [comment]
Thank you, didn't know this, works great! :-)

**Comment by domferr** [comment]
Great! Enjoy Tiling Shell!
