### ISSUE TITLE
[Feature Request] Show the snap assistant nearby the window

### ISSUE THREAD

**Issue by xevicb** [domferr/tilingshell#71]
Hi, and first of all, thanks for this amazing extension

I was wondering if have you considered to add multimonitor support, adding the possibility when editing a layout to choose in which monitor the windows has to be arranged.

It would be nice too, the possibility to choose the window with the layouts to appear whenever you start to drag a window.

Anyway, the extension is really useful as is.

**Comment by domferr** [comment]
Hey, thank you for your suggestions, I'm happy you are enjoying Tiling Shell!

Speaking about activating the tiling system on drag (without pressing any activation key) I have good news for you: you can enable it from the preferences, by selecting _(None)_ as the tiling system's activation key.

Speaking about editing layouts on multiple monitors setups: it is something I'd like to have too and it is tracked by [#34](https://github.com/domferr/tilingshell/issues/34), stay tuned!

**Comment by xevicb** [comment]
Wow, what a fast response! 

I've selected 'none' but when I drag the window it only let me arrange it in one of thev various arrangements I've set up. In my previous message I meant to say that the popup that actually appears when you drag the window to the top screen position, would be nice the possibility to choose to make it appear relative to the screen window position. 

Something similar to the screenshot I'm attaching

![Captura de pantalla 2024-07-05 142746](https://github.com/domferr/tilingshell/assets/20225309/56f419b5-eb60-43e1-8f46-a880eff1004d)

You can see the behaviour in this video as well. [https://www.youtube.com/watch?v=7Bl5sgcN0f8](url)
This video is from Asus, they handle the window management on multimonitor with they app screenxpert. In my opinion, they nailed the concept, but in Windows everything feels sluggish, I've experiencing a much more fluid OS with linux right now. 

I have Asus zenbook duo and as I said before, in its current state this extension is more than a lifesaver for me!

**Comment by domferr** [comment]
Hey, thank you for your suggestion! I'm happy you are enjoying Tiling Shell.

The video and the image are very useful, thanks for sharing. I think this may behave in some strange way with the tiling system itself: since the snap assistant would be on top of the window (or near it) it is not clear to the user how to use tiling system without activating the snap assistant.

However, it may be cool to show the snap assistant when you right click on the window! This is a mockup:

<p align="center">
<img src="https://github.com/domferr/tilingshell/assets/14203981/cf7baa53-3e9f-4de1-91f3-943239a4ee24" />
</p>

**Comment by domferr** [comment]
Let's continue the discussion on #77. Thank you

**Comment by xevicb** [comment]
@domferr, sorry for the delay, I've been out few days and now I see your right click proposal. This would be awesome! love your work
