### ISSUE TITLE
GSE 

### ISSUE THREAD

**Issue by in4matix** [domferr/tilingshell#8]
Thanks for this awesome extension! Stumbled across it by chance. Seems to work flawlessly on Ubuntu 22.04 (Gnome 42.9). You should definitely consider uploading to GSE. Be warned though, the bleeding edge cutters are going to overwhelm you to make it work on Gnome 46...

**Comment by domferr** [comment]
Hey, thank you for trying my extension! I much appreciate your feedback, it is very important for me.

Lately I have been working hard to open source this extension and to ensure it can be shipped to everyone, even for new Linux users! So yeah, I will definitely upload it. Moreover, this will happen soon since most of the things are done. I will definitely come back here with some updates in the next few weeks.

BTW the goal is to build an extension working on both GNOME 40-44 and 45+. I won't consider dropping support for GNOME 40-44. But yeah, this is gonna be hard as you pointed out :)

Feel free to open an issue for any bug or feature request: I will be more than glad to consider it!

**Comment by in4matix** [comment]
Good to hear that you are working on it and improving it. Definitely looking forward to future releases. 

Besides the issue of windows not restoring to their previous size, one other suggestion is to have a "No Tiling" option in the menu. Reason being that I often move small apps/windows around and I don't need to tile them...

**Comment by in4matix** [comment]
Hey, just checking in. I see you working on version 7. Can't wait to see what magic you have packed into an already perfect WM.
If you don't mind me asking, why haven't you published to Gnome Shell Extensions yet?

**Comment by domferr** [comment]
I didn't publish yet because I would like to change its name because it is an extension, not a window manager in the traditional sense understood in the Linux world (and the current name may cause confusion). Moreover some testing for specific GNOME version has to be done yet before publishing, because people testing unfinished extensions tend to share a bad review on GSE, even if the extension is not ready yet :\ 

> Can't wait to see what magic you have packed into an already perfect WM
Thank you, I am so happy you like it! :heart:

**Comment by in4matix** [comment]
Got some ideas for you: TileZone, MagicTiler, ZoneTiler, WinMan (Windows Manager), FancyTiler, TileMyWindows, DesktopZones.

**Comment by in4matix** [comment]
Just when I thought this Application could not be improved! Amazing dude! You rock!

**Comment by in4matix** [comment]
One more; ZoneMyWindows

**Comment by domferr** [comment]
I decided to name it **Tiling Shell** and to upload on GSE. Currently under [review](https://extensions.gnome.org/review/55479).

**Comment by in4matix** [comment]
Mmmm... I still like **Tile My Windows** , but good on you dude! This extension has now become a huge part of my daily workflow, and also one of my top best most useful extensions (out of 43). I wish you all the best going forward!

**Comment by domferr** [comment]
@in4matix I received your donation, wow thank you, I'm speechless! I'm happy you are enjoying this extension and your support means the world to me :heart:

**Comment by in4matix** [comment]
@domferr , only a pleasure, wish I could do more. I have added you to my regular donations list. I'm happy to support Dev's who produce awesome software and making it available for **free!!**

**Comment by domferr** [comment]
Here we are! 
https://extensions.gnome.org/extension/7065/tiling-shell/
